# Generated by Django 4.1.7 on 2023-03-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="term", new_name="semester",
        ),
    ]
